server:
  port: "8000"
  read_timeout: 10s
  write_timeout: 10s
  enable_print_routes: true
  max_header_megabytes: 1

postgres:
  username: "postgres"
  host: "localhost"
  port: "5436"
  db_name: "postgres"
  ssl_mode: "disable"

auth:
  jwt:
    access_token_ttl: 10m
    refresh_token_ttl: 1440h
