app:
  port: "8080"
  readTimeout: 10 * time.Second
  writeTimeout: 10 * time.Second
  enablePrintRoutes: true
  maxHeaderSize: 1 << 20

db:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"