server:
  port: "8000"
  readTimeout: 10s
  writeTimeout: 10s
  enablePrintRoutes: false
  maxHeaderMegabytes: 1

postgres:
  username: "postgres"
  host: "localhost"
  port: "5436"
  DBName: "postgres"
  SSLmode: "disable"

auth:
  jwt:
    accessTokenTTL: 10m
    refreshTokenTTL: 1440h
